'
'ClassDiagrams: Relations between classes
'Relations between classes are defined using the following symbols :
'Extension: <|--
'Composition: *--
'Aggregation: o--
'Composition Association: ..
'Extension Association: --
'Drawing
'It is possible to replace -- by .. to have a dotted line for associations:
'Knowing those rules, it is possible to draw the following drawings:
'--------------------------------------
'

@startuml
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
@enduml
