'
'ClassDiagrams: Labeling Relationship
'
'It is possible a add a label on the relation, using :, followed by the text of the label.
'For cardinality, you can use double-quotes "" on each side of the relation.
'
'--------------------------------------
'

@startuml
Class01 "1" *-- "many" Class02 : contains
Class03 o-- Class04 : aggregation
Class05 --> "1" Class06
@enduml
