'
'Sequence Digram: Message to Self
'
'A participant can send a message to itself.
'It is also possible to have multi-line using \n.
'
'--------------------------------------
'
@startuml

Alice->Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext

@enduml
