'
'Basics: Lifeline
'Lifeline Activation and Destruction
'activate:
'   The activate and deactivate are used to denote participant activation.
'   Once a participant is activated, its lifeline appears.
'destroy:
'   The destroy denote the end of the lifeline of a participant.
'The activate and deactivate apply on the previous message.
'
'Nested lifeline can be used, and it is possible to add a color on the lifeline.
'

@startuml
participant User
User -> A: DoWork

activate A #FFBBBB
    A -> A: Internal call
    activate A #DarkSalmon
        A -> B: << createRequest >>
        activate B
            B --> A: RequestCreated
        deactivate B
    deactivate A
A -> User: Done
deactivate A

@enduml