'
'UseCase: Changing arrows direction
'
'By default, links between classes have two dashes -- and are vertically oriented. It is possible to use horizontal
'link by putting a single dash (or dot) like this:
'
'-->
'->
'<--
'<-
'--------------------------------------
'

@startuml
:user: --> (Use case 1)
:user: -> (Use case 2)

' Change direction
(Use case 3) <.. :user:
(Use case 4) <- :user:

@enduml